data:
  build: mysql/data
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /etc/farmer/db:/var/lib/mysql
    - /etc/farmer/elk:/data
    - /etc/farmer/etcd:/var/etcd/data
    - /etc/farmer/revere_proxy/certs:/certs
    - /etc/farmer/docker:/root/.docker
    - /etc/farmer/gitkey:/root/.ssh
  environment:
    SERVICE_IGNORE: ignore

mysql_api:
  container_name: farmer_mysql_api
  build: mysql/api
  restart: always
  links:
    - mysql
  environment:
    SERVICE_IGNORE: ignore

mysql:
  container_name: farmer_mysql_server
  image: mysql:5.6
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    SERVICE_IGNORE: ignore
  volumes_from:
    - data

etcd:
  container_name: farmer_etcd_server
  image: quay.io/coreos/etcd:v2.2.1
  restart: always
  ports:
    - 2379:2379
  command:
    - -name=etcd
    - -data-dir=/var/etcd/data
    - -listen-client-urls=http://0.0.0.0:2379
    - -advertise-client-urls=http://farmer_etcd_server:2379
    - --debug=true
  volumes_from:
    - data
  environment:
    SERVICE_IGNORE: ignore

registrator:
  container_name: farmer_registrator
  image: gliderlabs/registrator:v6
  restart: always
  command: -internal -ttl 11 -ttl-refresh 10 -resync 10 etcd://farmer_etcd_server:2379/services
  links:
    - etcd
  volumes_from:
    - data
  environment:
    SERVICE_IGNORE: ignore

proxy:
  container_name: farmer_proxy_server
  restart: always
  build: proxy
  links:
    - etcd
  ports:
    - 80:80
  volumes_from:
    - data
  environment:
    ETCD_NODE: farmer_etcd_server:2379
    SERVICE_IGNORE: ignore
    MAIN_DOMAIN: ravaj.ir

browser:
  container_name: farmer_etcd_browser
  image: buddho/etcd-browser
  restart: always
  ports:
    - 8000:8000
  links:
    - etcd
  environment:
    ETCD_HOST: farmer_etcd_server
    ETCD_PORT: 2379
    SERVICE_IGNORE: ignore

toolbelt_daemon:
  build: ./toolbelt_daemon
  container_name: farmer_toolbelt_daemon
  restart: always
  links:
    - etcd
  volumes_from:
    - data
  environment:
    SERVICE_IGNORE: ignore

logger:
  image: nshou/elasticsearch-kibana
  restart: always
  container_name: farmer_logger
  ports:
    - 5601:5601
  volumes_from:
    - data