data:
  container_name: farmer_data
  restart: always
  build: mysql/data
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/tmp/docker.sock
    - /etc/farmer/db:/var/lib/mysql
    - /etc/farmer/logger/elasticsearch:/var/lib/elasticsearch
    - /etc/farmer/etcd:/var/etcd/data
    - /etc/farmer/proxy/certs:/certs
    - /etc/farmer/common/docker:/root/.docker
    - /etc/farmer/common/ssh:/root/.ssh
  environment:
    SERVICE_IGNORE: ignore

mysql_api:
  container_name: farmer_mysql_api
  restart: always
  build: mysql/api
  links:
    - mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    SERVICE_IGNORE: ignore

mysql:
  container_name: farmer_mysql_server
  restart: always
  build: mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    SERVICE_IGNORE: ignore
  volumes_from:
    - data

etcd:
  container_name: farmer_etcd_server
  restart: always
  image: quay.io/coreos/etcd:v2.2.1
  ports:
    - 2379:2379
  command:
    - -name=etcd
    - -data-dir=/var/etcd/data
    - -listen-client-urls=http://0.0.0.0:2379
    - -advertise-client-urls=http://farmer_etcd_server:2379
    - --debug=true
  volumes_from:
    - data
  environment:
    SERVICE_IGNORE: ignore

registrator:
  container_name: farmer_registrator
  restart: always
  image: gliderlabs/registrator:v6
  command: -internal -ttl 11 -ttl-refresh 10 -resync 10 etcd://farmer_etcd_server:2379/services
  links:
    - etcd
  volumes_from:
    - data
  environment:
    SERVICE_IGNORE: ignore

proxy:
  container_name: farmer_proxy_server
  restart: always
  build: proxy
  links:
    - etcd
  ports:
    - 80:80
    - 443:443
  volumes_from:
    - data
  environment:
    ETCD_NODE: farmer_etcd_server:2379
    SERVICE_IGNORE: ignore
    MAIN_DOMAIN: ravaj.ir

browser:
  container_name: farmer_etcd_browser
  restart: always
  image: buddho/etcd-browser
  ports:
    - 8000:8000
  links:
    - etcd
  environment:
    ETCD_HOST: farmer_etcd_server
    ETCD_PORT: 2379
    SERVICE_IGNORE: ignore

toolbelt_daemon:
  container_name: farmer_toolbelt_daemon
  restart: always
  build: ./toolbelt_daemon
  links:
    - etcd
  volumes_from:
    - data
  environment:
    SERVICE_IGNORE: ignore

logger:
  container_name: farmer_logger
  restart: always
  image: nshou/elasticsearch-kibana
  environment:
    SERVICE_IGNORE: ignore
  ports:
    - 5601:5601
  volumes_from:
    - data

mailer:
  container_name: farmer_mailer
  restart: always
  image: analogic/poste.io
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/farmer/mailer:/data
  environment:
    SERVICE_80_NAME: mailer/http
    SERVICE_443_NAME: mailer/https
  ports:
    - 80
    - 443
    - 25:25
    - 110:110
    - 143:143
    - 465:465
    - 587:587
    - 993:993
    - 995:995
