[template]
src         = "nginx.tmpl"
dest        = "/etc/nginx/conf.d/default.conf"
keys        = ["services"]
owner       = "nginx"
mode        = "0644"
check_cmd   = "if [ /usr/sbin/nginx -t ];then rm -f /etc/nginx/conf.d/default.conf; fi"
reload_cmd  = "service nginx reload"
